server:
  port: 80

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RewritePath= /(?<segment>.*) , /dev/v1/${segment}
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**